//
//  GeminiClient.swift
//  GemNote
//
//  HTTP client for Gemini API using URLSession with async/await.
//

import Foundation

/// Client for interacting with Google's Gemini AI API
final class GeminiClient {
    static let shared = GeminiClient()
    
    private let baseURL = "https://generativelanguage.googleapis.com/v1beta/models"
    private let timeout: TimeInterval = 30.0
    
    private init() {}
    
    // MARK: - Public Methods
    
    /// Generate content using the specified model
    /// - Parameters:
    ///   - prompt: The text prompt to send
    ///   - model: The Gemini model to use
    ///   - isDryRun: If true, returns mock data without making a network call
    /// - Returns: The generated text
    func generate(prompt: String, model: GeminiModel, isDryRun: Bool = false) async throws -> String {
        // Handle dry run mode
        if isDryRun {
            return generateDryRunResponse(for: prompt)
        }
        
        // Retrieve API key from Keychain
        guard let apiKey = try KeychainManager.shared.retrieve(forKey: KeychainManager.Keys.geminiAPIKey),
              !apiKey.isEmpty else {
            throw GemNoteError.noAPIKey
        }
        
        // Build request
        let url = buildURL(for: model, apiKey: apiKey)
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.timeoutInterval = timeout
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        
        // Create request body
        let geminiRequest = GeminiRequest.from(text: prompt)
        request.httpBody = try JSONEncoder().encode(geminiRequest)
        
        // Execute request
        let (data, response) = try await URLSession.shared.data(for: request)
        
        // Validate response
        guard let httpResponse = response as? HTTPURLResponse else {
            throw GemNoteError.invalidResponse
        }
        
        guard (200...299).contains(httpResponse.statusCode) else {
            // Try to parse error response
            if let errorResponse = try? JSONDecoder().decode(GeminiResponse.self, from: data),
               let error = errorResponse.error {
                throw NSError(
                    domain: "GeminiAPI",
                    code: error.code,
                    userInfo: [NSLocalizedDescriptionKey: error.message]
                )
            }
            throw GemNoteError.invalidResponse
        }
        
        // Parse response
        let geminiResponse = try JSONDecoder().decode(GeminiResponse.self, from: data)
        
        guard let text = geminiResponse.text else {
            throw GemNoteError.invalidResponse
        }
        
        return text.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    
    // MARK: - Private Methods
    
    private func buildURL(for model: GeminiModel, apiKey: String) -> URL {
        let endpoint = "\(baseURL)/\(model.rawValue):generateContent"
        var components = URLComponents(string: endpoint)!
        components.queryItems = [URLQueryItem(name: "key", value: apiKey)]
        return components.url!
    }
    
    private func generateDryRunResponse(for prompt: String) -> String {
        if prompt.contains("SUMMARY") && prompt.contains("TAGS") {
            return """
            SUMMARY: This is a dry run summary of the note content. In production, this would be generated by the AI model.
            TAGS: note, sample, test, dryrun, demo
            """
        } else if prompt.contains("Suggest") && prompt.contains("tags") {
            return "note, sample, test, dryrun, demo"
        } else {
            return "This is a dry run summary of the note content. In production, this would be generated by the AI model."
        }
    }
}

// MARK: - Response Parser

extension GeminiClient {
    /// Parse a combined summary and tags response
    struct ParsedResponse {
        let summary: String?
        let tags: [String]
        
        static func parse(_ text: String) -> ParsedResponse {
            var summary: String?
            var tags: [String] = []
            
            let lines = text.components(separatedBy: .newlines)
            
            for line in lines {
                let trimmedLine = line.trimmingCharacters(in: .whitespaces)
                
                if trimmedLine.hasPrefix("SUMMARY:") {
                    summary = trimmedLine
                        .replacingOccurrences(of: "SUMMARY:", with: "")
                        .trimmingCharacters(in: .whitespaces)
                } else if trimmedLine.hasPrefix("TAGS:") {
                    let tagString = trimmedLine
                        .replacingOccurrences(of: "TAGS:", with: "")
                        .trimmingCharacters(in: .whitespaces)
                    tags = tagString
                        .components(separatedBy: ",")
                        .map { $0.trimmingCharacters(in: .whitespaces) }
                        .filter { !$0.isEmpty }
                }
            }
            
            // If no structured format found, treat entire response as summary
            if summary == nil && tags.isEmpty {
                summary = text
            }
            
            return ParsedResponse(summary: summary, tags: tags)
        }
    }
}
