//
//  GeminiClient.swift
//  GemNote
//
//  Client for Gemini AI API integration
//

import Foundation

/// Client for making requests to Gemini AI API
final class GeminiClient {
    static let shared = GeminiClient()
    
    private let baseURL = "https://generativelanguage.googleapis.com/v1beta/models"
    private let timeout: TimeInterval = 30.0
    
    private init() {}
    
    // MARK: - Public Methods
    
    /// Generate a summary for the given text
    func generateSummary(
        for text: String,
        model: GeminiModel = .gemini15Flash,
        isDryRun: Bool = false
    ) async throws -> String {
        if isDryRun {
            return generateDryRunSummary(for: text)
        }
        
        let prompt = PromptBuilder.summarizePrompt(for: text)
        return try await generateContent(prompt: prompt, model: model)
    }
    
    /// Generate tag suggestions for the given text
    func generateTags(
        for text: String,
        model: GeminiModel = .gemini15Flash,
        isDryRun: Bool = false
    ) async throws -> [String] {
        if isDryRun {
            return generateDryRunTags(for: text)
        }
        
        let prompt = PromptBuilder.tagSuggestionPrompt(for: text)
        let response = try await generateContent(prompt: prompt, model: model)
        
        // Parse comma-separated tags
        let tags = response
            .components(separatedBy: ",")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        
        return Array(tags.prefix(5))
    }
    
    // MARK: - Private Methods
    
    private func generateContent(prompt: String, model: GeminiModel) async throws -> String {
        guard let apiKey = KeychainManager.shared.geminiAPIKey, !apiKey.isEmpty else {
            throw GemNoteError.noAPIKey
        }
        
        let urlString = "\(baseURL)/\(model.apiEndpoint):generateContent?key=\(apiKey)"
        guard let url = URL(string: urlString) else {
            throw GemNoteError.invalidAPIKey
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = timeout
        
        let requestBody = GeminiRequest(
            contents: [
                GeminiRequest.Content(
                    parts: [
                        GeminiRequest.Content.Part(text: prompt)
                    ]
                )
            ]
        )
        
        request.httpBody = try JSONEncoder().encode(requestBody)
        
        let (data, response) = try await URLSession.shared.data(for: request)
        
        guard let httpResponse = response as? HTTPURLResponse else {
            throw GemNoteError.invalidResponse
        }
        
        guard httpResponse.statusCode == 200 else {
            let errorMessage = String(data: data, encoding: .utf8) ?? "Unknown error"
            throw GemNoteError.aiRequestFailed("Status \(httpResponse.statusCode): \(errorMessage)")
        }
        
        let geminiResponse = try JSONDecoder().decode(GeminiResponse.self, from: data)
        
        if let error = geminiResponse.error {
            throw GemNoteError.aiRequestFailed(error.message)
        }
        
        guard let text = geminiResponse.text, !text.isEmpty else {
            throw GemNoteError.invalidResponse
        }
        
        return text
    }
    
    // MARK: - Dry Run Simulation
    
    private func generateDryRunSummary(for text: String) -> String {
        let wordCount = text.components(separatedBy: .whitespacesAndNewlines).filter { !$0.isEmpty }.count
        return "[DRY RUN] This is a simulated summary of your note. Word count: \(wordCount). In production, this would be generated by Gemini AI."
    }
    
    private func generateDryRunTags(for text: String) -> [String] {
        return ["dry-run", "test", "simulated", "demo"]
    }
}
